import pandas as pd
import json
from jsonschema import validate, ValidationError
import great_expectations as ge

# Load CSV
df = pd.read_csv("raw_data.csv")

# Standardize columns
df["Transaction Date"] = pd.to_datetime(df["Transaction Date"], errors="coerce")
df["Price Per Unit"] = pd.to_numeric(df["Price Per Unit"], errors="coerce")
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")
df["Total Spent"] = pd.to_numeric(df["Total Spent"], errors="coerce")

# Load schema
with open("schema.json") as f:
    schema = json.load(f)

# JSON Schema validation
invalid_rows = []
for index, row in df.iterrows():
    try:
        validate(instance=row.to_dict(), schema=schema)
    except ValidationError:
        invalid_rows.append(index)

# Great Expectations checks
ge_df = ge.from_pandas(df)

ge_df.expect_column_values_to_not_be_null("Transaction ID")
ge_df.expect_column_values_to_not_be_null("Customer ID")
ge_df.expect_column_values_to_not_be_null("Transaction Date")
ge_df.expect_column_values_to_be_between("Price Per Unit", min_value=0)
ge_df.expect_column_values_to_be_between("Quantity", min_value=0)
ge_df.expect_column_values_to_be_between("Total Spent", min_value=0)

results = ge_df.validate()

# Save invalid records
df.loc[invalid_rows].to_csv("invalid_records.csv", index=False)

# HTML report (Improved UI)
null_summary = df.isnull().sum().to_frame("Null Count").to_html(
    classes="table", border=0
)

# HTML report (Improved UI with UTF-8 support)
null_summary = df.isnull().sum().to_frame("Null Count").to_html(
    classes="table", border=0
)

html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Data Quality Report</title>
    <style>
        body {{
            font-family: Arial, Helvetica, sans-serif;
            background-color: #f4f6f8;
            margin: 0;
            padding: 0;
        }}
        .container {{
            max-width: 900px;
            margin: 40px auto;
            background: #ffffff;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
        }}
        h1 {{
            text-align: center;
            color: #2c3e50;
        }}
        .summary {{
            display: flex;
            justify-content: space-between;
            margin: 30px 0;
        }}
        .card {{
            flex: 1;
            background: #f8f9fa;
            margin: 0 10px;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
            box-shadow: 0 2px 5px rgba(0,0,0,0.08);
        }}
        .card h2 {{
            margin: 0;
            color: #34495e;
        }}
        .card p {{
            font-size: 24px;
            font-weight: bold;
            color: #1abc9c;
            margin-top: 10px;
        }}
        .section {{
            margin-top: 40px;
        }}
        .section h2 {{
            color: #2c3e50;
            border-bottom: 2px solid #e0e0e0;
            padding-bottom: 8px;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }}
        th, td {{
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }}
        th {{
            background-color: #f1f1f1;
        }}
        .status {{
            margin-top: 30px;
            padding: 15px;
            border-radius: 6px;
            text-align: center;
            font-size: 18px;
            font-weight: bold;
            color: {"#27ae60" if results["success"] else "#e74c3c"};
            background-color: {"#eafaf1" if results["success"] else "#fdecea"};
        }}
        footer {{
            margin-top: 40px;
            text-align: center;
            font-size: 14px;
            color: #888;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>📊 Data Quality Report</h1>

        <div class="summary">
            <div class="card">
                <h2>Total Records</h2>
                <p>{len(df)}</p>
            </div>
            <div class="card">
                <h2>Invalid Records</h2>
                <p>{len(invalid_rows)}</p>
            </div>
        </div>

        <div class="section">
            <h2>Null Value Summary</h2>
            {null_summary}
        </div>

        <div class="status">
            Validation Status: {"SUCCESS ✅" if results["success"] else "FAILED ❌"}
        </div>

        <footer>
            Generated by Data Standardization & Cleansing Framework
        </footer>
    </div>
</body>
</html>
"""

# IMPORTANT: UTF-8 encoding to support emojis on Windows
with open("data_quality_report.html", "w", encoding="utf-8") as f:
    f.write(html_content)

print("Data quality framework executed successfully.")


